### ISSUE TITLE
Curriculum development sprint Sept 2015 

### ISSUE THREAD

**Issue by hlapp** [Reproducible-Science-Curriculum/planning#1]
We will be holding a [curriculum development virtual sprint](https://github.com/Reproducible-Science-Curriculum/planning/wiki/Curriculum-development-sprint-Sep-2015) on Sep 16, 2015. This issue is to track to-dos and other pre-event actions, as well as other preparations for this event.

Participants so far:
- Jenny Bryan (@jennybc)
- Mine Çetinkaya-Rundel (@mine-cetinkaya-rundel)
- Hilmar Lapp (@hlapp)
- François Michonneau (@fmichonneau)
- Pat Schloss (@pschloss)
- Tracy Teal (@tracykteal)
- Naupaka Zimmerman (@naupaka)
- Karen Cranston (@kcranston)

**Comment by hlapp** [comment]
Created [Google Hangout event](https://plus.google.com/events/c4lltdrva4ghml5secs3e2r3r8c?authkey=CP_XppzQ0aK7sgE).

**Comment by kcranston** [comment]
Created [etherpad](https://etherpad.mozilla.org/j9EklQZW1M)

**Comment by jennybc** [comment]
Just FYI: I will be able to join this virtual event from late morning to mid afternoon _my time_. So unfortunately you can't expect me on the hangout or etherpad earlier than that. I would like to work on the file naming material but will see how that fits with what the group has discussed/planned, once I come online.

**Comment by mine-cetinkaya-rundel** [comment]
Revisions to [rr-intro](https://github.com/Reproducible-Science-Curriculum/rr-intro):
- [x] remove any text that is workshop specific so the slides can be used in multiple settings easily
- [x] add instructions to "Exercise 1 - Identify pain points in getting your analysis to be reproducible" for participants who may not routinely do these tasks
- [x] add an actual data error to the dataset for Exercise 1 so that one of the tasks is actual data clean-up, and not just visualization
- [x] remove hands on RMarkdown exercise that relies on understanding R code, turn it into a demo - this will help make the intro lesson language agnostic, except for the RMarkdown demo (as mentioned in [#10](https://github.com/Reproducible-Science-Curriculum/rr-intro/issues/10))
- [x] any necessary revisions to accommodate varying levels of R background of participants
- [x] name intro-01 "motivating reproducibility" and intro-02 "reproducibility toolkit" so that intro-02 can be swapped out with another language version if need be

**Comment by naupaka** [comment]
[rr-organization1](https://github.com/Reproducible-Science-Curriculum/rr-organization1) is now split into [rr-organization1](https://github.com/Reproducible-Science-Curriculum/rr-organization1) and [rr-literate-programming](https://github.com/Reproducible-Science-Curriculum/rr-literate-programming)

**Comment by hlapp** [comment]
Event took place and is wrapped up.
